# Generated by Django 5.0.6 on 2024-05-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('period', models.CharField(choices=[('каждый день', 'Every Day'), ('несколько дней', 'Some Days'), ('раз в неделю', 'Every Week')], default='Каждый день', max_length=255, verbose_name='Период')),
                ('award', models.TextField(blank=True, null=True, verbose_name='Награда')),
                ('time_to_complete', models.TimeField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('sign_pleasand_habit', models.BooleanField(default=True, verbose_name='Признак приятной привычки')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='связаная привычка')),
            ],
        ),
    ]
