# Generated by Django 5.0.6 on 2024-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='sign_pleasand_habit',
            field=models.BooleanField(default=False, verbose_name='Признак приятной привычки'),
        ),
    ]
