# Generated by Django 5.0.6 on 2024-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_sign_pleasand_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('Каждый день', 'Every Day'), ('Несколько дней', 'Some Days'), ('Раз в неделю', 'Every Week')], default='Каждый день', max_length=255, verbose_name='Период'),
        ),
    ]
