# Generated by Django 5.0.6 on 2024-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_alter_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление'),
        ),
    ]
